name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - name: Linux build
        run: zig build -Drelease-safe -Dtarget=x86_64-linux-musl -Dcpu=baseline
      - name: Windows build
        run: zig build -Drelease-safe -Dtarget=x86_64-windows-gnu -Dcpu=baseline
      - name: macOS build
        run: zig build -Drelease-safe -Dtarget=x86_64-macos-gnu -Dcpu=baseline
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          path: zig-out/
